---
- hosts: all
  become: yes
  roles:
     - { role: archcore, tags: ['core', 'cli', 'gui'] }
     - { role: x, tags: ['x', 'gui'] }
     - { role: tools, tags: ['tools', 'gui'] }
     - { role: audio, tags: ['audio', 'cli', 'gui'] }
     - { role: ops, tags: ['ops', 'cli', 'gui'] }
     - { role: dev, tags: ['dev', 'python', 'cli', 'gui'] }
     - { role: comm, tags: ['comm', 'cli', 'gui'] }
     - { role: media, tags: ['media', 'cli', 'gui'] }